# Render Blueprint Configuration
services:
  - type: web
    name: canary-backend
    env: node
    region: frankfurt
    plan: starter
    buildCommand: cd backend && npm install && npx prisma generate
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: PORT
        value: 4000
    autoDeploy: true
    healthCheckPath: /api/health
